const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:JSON_HEADERS});
const now=()=>new Date().toISOString();
const randomCode=(length=12)=>{const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";const values=new Uint32Array(length);crypto.getRandomValues(values);return [...values].map(value=>chars[value%chars.length]).join("")};
const randomToken=()=>crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-","");
async function sha256(value){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
async function parseBody(request){const length=Number(request.headers.get("content-length")||0);if(length>600000)throw new Error("PAYLOAD_TOO_LARGE");return request.json()}
function cleanSnapshot(value){if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("SNAPSHOT_INVALID");const text=JSON.stringify(value);if(text.length>500000)throw new Error("PAYLOAD_TOO_LARGE");return text}
async function authenticate(request,env){const header=request.headers.get("authorization")||"";const token=header.startsWith("Bearer ")?header.slice(7):"";if(!token)return null;const tokenHash=await sha256(token);return env.DB.prepare("SELECT d.archive_id,a.name FROM cloud_devices d JOIN cloud_archives a ON a.id=d.archive_id WHERE d.token_hash=? AND d.revoked_at IS NULL").bind(tokenHash).first()}
async function createArchive(request,env){const body=await parseBody(request);const name=String(body.name||"Il mio archivio").trim().slice(0,40)||"Il mio archivio";const payload=cleanSnapshot(body.snapshot||{});const id=crypto.randomUUID();let recoveryCode,recoveryHash;for(let attempt=0;attempt<8;attempt++){recoveryCode=randomCode();recoveryHash=await sha256(recoveryCode);const found=await env.DB.prepare("SELECT 1 FROM cloud_archives WHERE recovery_code_hash=?").bind(recoveryHash).first();if(!found)break}const token=randomToken(),tokenHash=await sha256(token),created=now();await env.DB.batch([env.DB.prepare("INSERT INTO cloud_archives(id,name,recovery_code_hash,created_at,updated_at) VALUES(?,?,?,?,?)").bind(id,name,recoveryHash,created,created),env.DB.prepare("INSERT INTO cloud_devices(id,archive_id,token_hash,created_at) VALUES(?,?,?,?)").bind(crypto.randomUUID(),id,tokenHash,created),env.DB.prepare("INSERT INTO cloud_snapshots(archive_id,revision,payload,updated_at) VALUES(?,?,?,?)").bind(id,1,payload,created)]);return json({archiveId:id,archiveName:name,recoveryCode,token,revision:1,updatedAt:created})}
async function joinArchive(request,env){const body=await parseBody(request);const recoveryCode=String(body.recoveryCode||"").replace(/[^A-Z0-9]/gi,"").toUpperCase();const recoveryHash=await sha256(recoveryCode);const archive=await env.DB.prepare("SELECT id,name FROM cloud_archives WHERE recovery_code_hash=?").bind(recoveryHash).first();if(!archive)return json({error:"Codice non valido."},404);const token=randomToken(),tokenHash=await sha256(token),created=now();await env.DB.prepare("INSERT INTO cloud_devices(id,archive_id,token_hash,created_at) VALUES(?,?,?,?)").bind(crypto.randomUUID(),archive.id,tokenHash,created).run();const snapshot=await env.DB.prepare("SELECT revision,payload,updated_at FROM cloud_snapshots WHERE archive_id=?").bind(archive.id).first();return json({archiveId:archive.id,archiveName:archive.name,recoveryCode,token,revision:snapshot?.revision||0,snapshot:JSON.parse(snapshot?.payload||"{}"),updatedAt:snapshot?.updated_at||null})}
async function rotateRecoveryCode(env,member){let recoveryCode,recoveryHash;for(let attempt=0;attempt<8;attempt++){recoveryCode=randomCode();recoveryHash=await sha256(recoveryCode);const found=await env.DB.prepare("SELECT 1 FROM cloud_archives WHERE recovery_code_hash=?").bind(recoveryHash).first();if(!found)break}const updatedAt=now();await env.DB.prepare("UPDATE cloud_archives SET recovery_code_hash=?,updated_at=? WHERE id=?").bind(recoveryHash,updatedAt,member.archive_id).run();return json({recoveryCode,updatedAt})}
async function getSnapshot(env,member){const snapshot=await env.DB.prepare("SELECT revision,payload,updated_at FROM cloud_snapshots WHERE archive_id=?").bind(member.archive_id).first();return json({revision:snapshot?.revision||0,snapshot:JSON.parse(snapshot?.payload||"{}"),updatedAt:snapshot?.updated_at||null})}
async function putSnapshot(request,env,member){const body=await parseBody(request);const payload=cleanSnapshot(body.snapshot||{});const current=await env.DB.prepare("SELECT revision FROM cloud_snapshots WHERE archive_id=?").bind(member.archive_id).first();const revision=Number(current?.revision||0);if(Number(body.baseRevision||0)!==revision)return json({error:"CONFLICT",revision},409);const next=revision+1,updatedAt=now();await env.DB.batch([env.DB.prepare("UPDATE cloud_snapshots SET revision=?,payload=?,updated_at=? WHERE archive_id=?").bind(next,payload,updatedAt,member.archive_id),env.DB.prepare("UPDATE cloud_archives SET updated_at=? WHERE id=?").bind(updatedAt,member.archive_id)]);return json({revision:next,updatedAt})}

export default{async fetch(request,env){try{const url=new URL(request.url);if(url.pathname==="/api/health")return json({ok:true,service:"Gestione Spese Cloud"});if(url.pathname==="/api/archives"&&request.method==="POST")return createArchive(request,env);if(url.pathname==="/api/archives/join"&&request.method==="POST")return joinArchive(request,env);if(url.pathname.startsWith("/api/")){const member=await authenticate(request,env);if(!member)return json({error:"TOKEN_INVALID"},401);if(url.pathname==="/api/sync"&&request.method==="GET")return getSnapshot(env,member);if(url.pathname==="/api/sync"&&request.method==="PUT")return putSnapshot(request,env,member);if(url.pathname==="/api/recovery-code"&&request.method==="POST")return rotateRecoveryCode(env,member);return json({error:"API non trovata"},404)}return env.ASSETS.fetch(request)}catch(error){const code=error?.message||"Errore interno";const status=code==="PAYLOAD_TOO_LARGE"?413:code==="SNAPSHOT_INVALID"?400:500;console.error(error);return json({error:code},status)}}};
